spring.application.name=Nutrilio
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/nutrilio_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.ai.openai.api-key=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